name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  powershell-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run PowerShell tests
        shell: pwsh
        run: ./run-all-tests.ps1

  shell-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run shell tests
        shell: bash
        run: ./run-all-tests.sh
